require 'zlib'
require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'

#making a connenctiont oour db
ActiveRecord::Base.establish_connection(
		:adapter => 'sqlite3',
		:database => 'pottyproject.db'
)